// Deterministic, offline LLM provider for automated testing. The existing unit-test
// suites reach into the module graph directly via vi.doMock('../llm/index.js', ...) to
// stub Gemini out (see e.g. listing-generator/index.idempotency.test.js) — that works
// because those tests run in the same Node process as the code under test. Playwright
// E2E tests don't have that option: they drive the whole app through a real browser
// against a real, separately-spawned backend process, so there's no import graph to
// mock into.
//
// This fixture provider is the fix — selected via LLM_PROVIDER=fixture, the same
// swappable-interface mechanism already used to choose gemini vs claude (see
// getActiveProvider() in ./index.js). No network call, no API key, no cost, and no
// flakiness from a real model's output varying between runs — output is fixed rather
// than generated, which is exactly what a critical-path E2E suite needs (see
// ARCHITECTURE.md -> Testing & CI/CD -> "a small set of Playwright end-to-end tests
// covering the critical path only").
import { LISTING_VARIATIONS } from '../../config/shop-conventions.js';

function fixtureListingVariations() {
  return LISTING_VARIATIONS.map((angle) => ({
    angle,
    title: `${angle.replace('_', ' ')} fixture title`,
    description: `${angle.replace(
      '_',
      ' '
    )} fixture description, generated by the fixture LLM provider for automated tests — no real Gemini call was made.`,
    tags: Array.from({ length: 13 }, (_, i) => `${angle}-tag-${i}`),
    tag_alternates: Array.from({ length: 5 }, (_, i) => `${angle}-alt-${i}`),
  }));
}

function fixtureImageAnalysis() {
  return { subject: 'a fixture artwork', style: 'test style', palette: ['blue', 'white'], mood: 'calm' };
}

// Called by both Module 2 (listing generator — prompt asks for a "variations" JSON
// array, see listing-generator/prompt.js) and Module 4 (prompt helper — plain
// Midjourney-formatted text, no JSON). `options.json` alone doesn't disambiguate which
// module is calling, so this inspects the prompt text itself for the one string unique
// to Module 2's requested response shape.
export async function generateText(prompt) {
  if (/"variations"/.test(prompt)) {
    return {
      text: JSON.stringify({ variations: fixtureListingVariations() }),
      provider: 'fixture',
      model: 'fixture',
    };
  }
  // Generic fallback (e.g. Module 4's prompt helper) — plain text, not JSON, since that
  // module doesn't request options.json either.
  return { text: 'fixture prompt text --v 7 --style raw --ar 1:1 --s 100', provider: 'fixture', model: 'fixture' };
}

// Module 1 (Image Analyzer). Doesn't need to actually read imagePath — the point is to
// avoid a real network call entirely, not to produce a realistic analysis of the
// specific uploaded file.
export async function generateVision() {
  return { text: JSON.stringify(fixtureImageAnalysis()), provider: 'fixture', model: 'fixture' };
}

// Module 3's AI-outpainting fallback has no fixture equivalent — out of scope for the
// critical-path E2E suite (ARCHITECTURE.md's Playwright scope is upload → listing →
// review → copy-to-clipboard, not the mockup-composer's large-mismatch AI path). Throws
// clearly rather than silently returning fake image bytes, so a test that unexpectedly
// hits this path fails loudly instead of asserting against meaningless data.
export async function generateImage() {
  throw new Error(
    'generateImage() is not implemented in the fixture LLM provider (LLM_PROVIDER=fixture) — Module 3 ' +
      'AI-outpainting is out of scope for the E2E critical-path suite. Use LLM_PROVIDER=gemini for that.'
  );
}
